### ISSUE TITLE
No Linux Build

### ISSUE THREAD

**Issue by ghost** [natrixdev/python-name-generator#1]
AttributeError: module 'platform' has no attribute '**linux_distribution**'  <-----  Error in Terminal

Hey can you make a **build** for **linux** .

-- Thanks miloszlip

**Comment by natrixdev** [comment]
> AttributeError: module 'platform' has no attribute '**linux_distribution**'  <-----  Error in Terminal
> 
> 
> 
> Hey can you make a **build** for **linux** .
> 
> 
> 
> -- Thanks miloszlip

Yeah, linux build will come soon !

**Comment by ghost** [comment]
Oh nice bro

**Comment by ghost** [comment]
I wanna make RPG game and it will be very helpful for making a character ^⁠_⁠^

**Comment by natrixdev** [comment]
> I wanna make RPG game and it will be very helpful for making a character ^⁠_⁠^

Ok, nice project btw

**Comment by natrixdev** [comment]
> Oh nice bro

np :)

**Comment by ghost** [comment]
It's working rn ??

**Comment by natrixdev** [comment]
> It's working rn ??

Yeah, It will work rn.
Follow this documentation to install python https://docs.python-guide.org/starting/install3/linux/
And then just run scripts
